services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  HeimrichHannot\IsotopeExtensionBundle\:
    resource: '../../{Attribute,Controller,DataContainer,EventListener,Manager}/*'
